import './init/api.init';
import './init/update_check';
import './init/fix_auth_cookie';
import './module/sw-settings-security';
import './fixes/next9242';
import './fixes/next12824';
import './fixes/next14883';
import './fixes/next15675';
import './fixes/next20305';
