framework:
    messenger:
        failure_transport: failed
        transports:
            failed: 
                dsn: 'enqueue://failed'
    cache:
        prefix_seed: shopware
        app: cache.adapter.redis
	system: cache.adapter.redis
        default_redis_provider: "redis://localhost:6379"
        pools:
            serializer:
                adapter: cache.adapter.redis
            annotations:
                adapter: cache.adapter.redis
            property_info:
                adapter: cache.adapter.redis
            messenger:
                adapter: cache.adapter.redis
            property_access:
                adapter: cache.adapter.redis
            cache.object:
                default_lifetime: 3600
                adapter: cache.app
                tags: cache.tags
            cache.http:
                default_lifetime: 3600
                adapter: cache.app
                tags: cache.tags
            cache.tags:
                adapter: cache.app
            cache.serializer:
                adapter: cache.app
            cache.property_info:
                adapter: cache.app    
            cache.property_access:
                adapter: cache.app                         

